plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'com.fotocesta.app'
    compileSdk 36

    defaultConfig {
        applicationId "com.fotocesta.app"
        minSdk 26
        targetSdk 36
        versionCode Integer.parseInt(System.getenv("GITHUB_RUN_NUMBER") ?: "1")
        versionName "1." + (System.getenv("GITHUB_RUN_NUMBER") ?: "0")
    }

    signingConfigs {
        fija {
            storeFile file("fotocesta.jks")
            storePassword "fotocesta"
            keyAlias "fotocesta"
            keyPassword "fotocesta"
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.fija
        }
        debug {
            signingConfig signingConfigs.fija
        }
    }

    lint {
        checkReleaseBuilds false
        abortOnError false
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'androidx.core:core-ktx:1.13.1'
    implementation 'androidx.activity:activity-ktx:1.9.1'
    implementation 'androidx.webkit:webkit:1.11.0'
}
